### ISSUE TITLE
Format of coverage CSV

### ISSUE THREAD

**Issue by ziels** [Serka-M/mmlong2#4]
Hey there, 

Thanks for this wonderful tool / workflow! 

I am wondering if you can elaborate on what format is needed for the coverage CSV file? (e.g. rows = contigs, columns = samples, values = coverage, or something else ?). From the documentation it also sounds like it may possible to provide a path to .fastq files instead of a CSV, which I would assume it then uses for mapping and generating the coverage CSV?

Thanks for the clarification! 

~ Ryan

**Comment by Serka-M** [comment]
Hey Ryan,

Thank you for your interest in the workflow.

An example of the CSV file for differential coverage binning is presented below.

```
PB,/path/to/your/reads/file1.fastq
NP,/path/to/your/reads/file2.fastq
IL,/path/to/your/reads/file3.fastq.gz
```
 
Essentially, the first column denotes the type of the reads, so that the workflow could pick optimal mapping settings: `PB` for long, accurate reads (eg. HiFi and maybe Nanopore duplex), `NP` for Nanopore simplex reads, `IL` for short, accurate reads.

The second column is an absolute path to your read files.

The workflow can run with compressed (gzipped) and uncompressed read files.
If you want to use paired-end short reads for binning, please interleave them into a single file.

Hope that answers your questions!

Best,
Mantas

**Comment by ziels** [comment]
Thanks so much for this clarification -- I've got it working on my end now! 

Cheers
~ Ryan
